//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadExamen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Calificaciones
    {
        public int pk_calificaciones { get; set; }
        public int fk_maestro { get; set; }
        public int fk_alumno { get; set; }
        public int fk_materia { get; set; }
        public decimal calificacion { get; set; }
        public string observaciones { get; set; }
    
        public virtual tb_Alumno tb_Alumno { get; set; }
        public virtual tb_Maestro tb_Maestro { get; set; }
        public virtual tb_Materia tb_Materia { get; set; }
    }
}
